### ISSUE TITLE
Having trouble using the package on a site using vue.js.

### ISSUE THREAD

**Issue by kwindo** [RyanDaDeng/laravel-google-recaptcha-v3#18]
Hi there,

Thanks for the package.

I managed to install it nicely on a new Laravel install but on the project I was planning on using it, which uses vue.js it's is giving me issues.

I tried adding {!!  GoogleReCaptchaV3::render(['signup_id'=>'signup']) !!} to the footer of my below the main app.js file in the footer of my site and in the <head> tag.

The component seems to work nicely but I'm running into "Error: reCAPTCHA placeholder element must be an element or id" on every page that doesn't have the <div id="signup_id"></div> tag. 

I'm assuming I need to use the vue file but I don't know how to implement it.

Could you provide some documentation on how to use the vue file?

Thanks!

**Comment by RyanDaDeng** [comment]
Hi, I just wake up, will help you on it. The vue component is not documented in readme, I’m sorry about it. Let me update it. Will let you know by today.

**Comment by RyanDaDeng** [comment]
@kwindo I have just updated document, can you go to this link: https://github.com/RyanDaDeng/laravel-google-recaptcha-v3#vue-usage

Let me know if you still have confusions.

Basically, you need to use the GoogleReCaptchaV3 vue component in your signup page (you mentioned you put it in app.js where its a global vue js file that does not support any Laravel blade directives)

Blade way that you see {{}} or {!! !!} is mostly like an PHP injection from your back-end logic, so the front-end and back-end is strongly coupled together in this case.

However, since vue.js aims at SPA and decoupled from back-end. So any communications between front-end and back-end is no longer possible. (yeah..there is still a way to do that but I think that is a bad practice so I am not going to mention here)

A drawback for using Vue component is that some of settings from Config file e.g. inline style, site key are no longer being shared with vue, so you need to manually pass these values as props into GoogleRecaptchaV3 component.

**Comment by kwindo** [comment]
Wow you are fast! Thanks so much, this is a great help.

I had to make some changes to make it work though. I kept getting the error "Error: reCAPTCHA placeholder element must be an element or id" and messages from vue about the props being in CamelCase. So I changed the props to lowercase.

The "action" prop was also missing in GoogleReCaptchaV3.vue so I added it and updated the "execute()" method to...

`
execute() {
                window.grecaptcha.ready(function () {
                    grecaptcha.execute(this.gAssignedId, {
                        action: this.action
                    });
                }.bind(this));
            },
`
I am calling the component in my app.js like...
`
Vue.component('google-re-captcha-v3', require('./components/Auth/GoogleReCaptchaV3.vue')); // I moved the location of the file
`
So it seems there's no need to import it in the form component.
`
import GoogleReCaptchaV3 from '../../components/Auth/GoogleReCaptchaV3.vue';
components: {
		GoogleReCaptchaV3
	},
`
At least, when I remove the import code it still seems to work.

**Comment by kwindo** [comment]
> By the way, for the missing action which is my bad, I updated the version recently, you should need to run composer update to get the latest version and publish the file again. Sorry about my bad.

Hej, that's ok. No neet to apologise. Glad I could help pointing that out.

Yep all good. Thanks for your help!

**Comment by RyanDaDeng** [comment]
Thanks @kwindo 👍
