### ISSUE TITLE
Curl Error Code: GoogleReCaptchaV3::messages.ERROR_TIMEOUT

### ISSUE THREAD

**Issue by TechTailor** [RyanDaDeng/laravel-google-recaptcha-v3#45]
Configured my app as described. Tried using with rendorOne, rendor and even rendorField, all of them giving the same error -

`Curl Error Code: GoogleReCaptchaV3::messages.ERROR_TIMEOUT`

Have {!!  GoogleReCaptchaV3::init() !!} at the bottom of my page.

Using Laravel 5.7.28

Please guide me through this.

Thanks in advance.

**Comment by RyanDaDeng** [comment]
I will check it for you tonight. Thank you for using the package.

**Comment by TechTailor** [comment]
Ok thanks. Waiting for an update.

**Comment by RyanDaDeng** [comment]
@TechTailor I tried to reproduce your env and problems.

Potential problems:

- Double check if you can access `https://www.google.com/recaptcha/api/siteverify`, just click this link if you can see any response. If not, which means you might not be able to access google, or your region got blocked. Google provides alternative links for different countries. Just let me know if you have this issue.

Can you also try to make a new Laravel app and follow the following steps that I did:

1. Install v5.7.28 for Laravel.
2. Install recaptcha package
3. Publish config file
4. Copy your v3 recaptcha secret and key to config file (ensure you are using v3 not v2)
5. Create a blade with:
```
<html>
<form method="POST" action="/verify">
    @csrf
    {!!  GoogleReCaptchaV3::renderField('contact_us_id','contact_us_action') !!}
    <input type="submit" value="submit">
</form>

{!! GoogleReCaptchaV3::init() !!}

</html>
```

6. register two routes in web:
```
Route::get('/home', 'HomeController@index')->name('home');
Route::post('/verify', 'HomeController@verify')->name('verify');
```
7. create controller function (without middleware)
```
    public function verify(Request $request){

        $rule = [
            'g-recaptcha-response' => [new GoogleReCaptchaV3ValidationRule()]
        ];

        $a = Validator::make($request->all(),$rule);

        dd($a->errors());
    }

    public function index()
    {
        return view('home');
    }
```

8.. open `/home`, you should see a recaptcha badge at the left corner
9. click submit, if you see message bug is empty them it works


Note: I have fixed the message errors. You can update the package, now you should see 'timeout' error instead of seeing constants.
